// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kagfzkphhezxljgqyjys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthZ2Z6a3BoaGV6eGxqZ3F5anlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODcyMTgsImV4cCI6MjA3MjQ2MzIxOH0.TZOgiY4s8OqtEAfs60Vs5PHVYU9B7NbUWYWXr-Why3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});